name: auto_acr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - imageio
  - opencv
  - tqdm
  - pillow
  - tifffile
  - pip:
      - torch
      - torchvision
      - torchaudio
      - rawpy
      - timm
